-- Calculating total revenue from delivered orders

SELECT SUM(oi.quantity * oi.price) AS total_revenue
FROM Order_Items oi
JOIN Orders o ON oi.order_id = o.order_id
WHERE o.status = 'Delivered';

-- Analyzing revenue generated by each customer

SELECT 
    c.customer_id,
    c.name,
    SUM(oi.quantity * oi.price) AS total_revenue
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
WHERE o.status = 'Delivered'
GROUP BY c.customer_id, c.name
ORDER BY total_revenue DESC;

-- Identifying top-selling products by quantity

SELECT 
    p.product_name,
    SUM(oi.quantity) AS total_sold
FROM Products p
JOIN Order_Items oi ON p.product_id = oi.product_id
JOIN Orders o ON oi.order_id = o.order_id
WHERE o.status = 'Delivered'
GROUP BY p.product_name
ORDER BY total_sold DESC;

-- Evaluating monthly revenue trends

SELECT 
    DATE_FORMAT(o.order_date, '%Y-%m') AS month,
    SUM(oi.quantity * oi.price) AS revenue
FROM Orders o
JOIN Order_Items oi ON o.order_id = oi.order_id
WHERE o.status = 'Delivered'
GROUP BY month
ORDER BY month;

-- Ranking customers based on revenue using window functions

SELECT 
    c.name,
    SUM(oi.quantity * oi.price) AS revenue,
    RANK() OVER (ORDER BY SUM(oi.quantity * oi.price) DESC) AS rnk
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
WHERE o.status = 'Delivered'
GROUP BY c.name;

-- Comparing RANK and DENSE_RANK behavior

SELECT 
    c.name,
    SUM(oi.quantity * oi.price) AS revenue,
    DENSE_RANK() OVER (ORDER BY SUM(oi.quantity * oi.price) DESC) AS rnk
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
WHERE o.status = 'Delivered'
GROUP BY c.name;

-- Assigning unique row numbers using ROW_NUMBER

SELECT 
    c.name,
    SUM(oi.quantity * oi.price) AS revenue,
    ROW_NUMBER() OVER (ORDER BY SUM(oi.quantity * oi.price) DESC) AS row_num
FROM Customers c
JOIN Orders o ON c.customer_id = o.customer_id
JOIN Order_Items oi ON o.order_id = oi.order_id
WHERE o.status = 'Delivered'
GROUP BY c.name;

-- Extracting top N customers based on revenue

SELECT *
FROM (
    SELECT 
        c.name,
        SUM(oi.quantity * oi.price) AS revenue,
        ROW_NUMBER() OVER (ORDER BY SUM(oi.quantity * oi.price) DESC) AS rn
    FROM Customers c
    JOIN Orders o ON c.customer_id = o.customer_id
    JOIN Order_Items oi ON o.order_id = oi.order_id
    WHERE o.status = 'Delivered'
    GROUP BY c.name
) t
WHERE rn <= 2;